server:
  port: 19005

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/todaktodag_db?currentSchema=care_plan_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: false

    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never