server:
  port: 19001

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: discharge_schema
        default_batch_fetch_size: 100
        hbm2ddl:
          create_namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never

  tracing:
    sampling:
      probability: 1.0

    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

logging:
  level:
    com.todak_todag.discharge_service: info

internal:
  key: ${INTERNAL_API_KEY}
