server:
  port: 19001

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:todaktodag_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: discharge_schema
        default_batch_fetch_size: 100
        format_sql: true
        hbm2ddl:
          create_namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never

  tracing:
    sampling:
      probability: 1.0

    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

logging:
  level:
    com.todak_todag.discharge_service: debug
