server:
  port: 19002

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      timeout: 3s

  jpa:
    open-in-view: false
    show-sql: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: social_worker_schema
        default_batch_fetch_size: 100
        hbm2ddl:
          create_namespaces: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    listener:
      simple:
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 1000ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:8761/eureka/

logging:
  level:
    com.todak_todag.social_worker_service: info

internal:
  key: ${INTERNAL_API_KEY}

matching:
  task:
    ttl: ${MATCHING_TASK_TTL:1h}
