server:
  port: 19002

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: social_worker_schema
        default_batch_fetch_size: 100
        hbm2ddl:
          create_namespaces: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: never

  tracing:
    sampling:
      probability: 1.0

    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:8761/eureka/

logging:
  level:
    com.todak_todag.social_worker_service: info

internal:
  key: ${INTERNAL_API_KEY}