## Java 21 실행 환경 사용.
#FROM eclipse-temurin:21-jre-alpine
#
## Healthcheck용 curl 설치.
#RUN apk add --no-cache curl
#
## 빌드된 JAR 경로 전달.
#ARG JAR_FILE
#
## JAR 파일 복사.
#COPY ${JAR_FILE} app.jar
#
## Config Server 실행.
#ENTRYPOINT ["java", "-jar", "/app.jar"]