server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: local

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/admin/users/**,/api/v1/auth/**,/api/v1/regions/**,/api/v1/admin/regions/**,/api/v1/consent-documents/**,/api/v1/admin/consent-documents/**,/api/v1/consents/**

            - id: discharge-service
              uri: lb://discharge-service
              predicates:
                - Path=/api/v1/discharges/**

            - id: social-worker-service
              uri: lb://social-worker-service
              predicates:
                - Path=/api/v1/social-worker-matchings/**

            - id: schedule-service
              uri: lb://schedule-service
              predicates:
                - Path=/api/v1/service-schedules/**,/api/v1/service-results/**

            - id: provider-service
              uri: lb://provider-service
              predicates:
                - Path=/api/v1/provide-services/**,/api/v1/service-offerings/**,/api/v1/provide-works/**,/api/v1/admin/service-offerings/**

            - id: care-plan-service
              uri: lb://care-plan-service
              predicates:
                - Path=/api/v1/care-plans/**,/api/v1/admin/care-plans/**,/api/v1/care-plan-services/**,/api/v1/service-preferences/**

            ## docs
            - id: user-service-docs
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - SetPath=/v3/api-docs

            - id: discharge-service-docs
              uri: lb://discharge-service
              predicates:
                - Path=/v3/api-docs/discharge-service
              filters:
                - SetPath=/v3/api-docs

            - id: social-worker-service-docs
              uri: lb://social-worker-service
              predicates:
                - Path=/v3/api-docs/social-worker-service
              filters:
                - SetPath=/v3/api-docs

            - id: schedule-service-docs
              uri: lb://schedule-service
              predicates:
                - Path=/v3/api-docs/schedule-service
              filters:
                - SetPath=/v3/api-docs

            - id: provider-service-docs
              uri: lb://provider-service
              predicates:
                - Path=/v3/api-docs/provider-service
              filters:
                - SetPath=/v3/api-docs

            - id: care-plan-service-docs
              uri: lb://care-plan-service
              predicates:
                - Path=/v3/api-docs/care-plan-service
              filters:
                - SetPath=/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - { name: user, url: /v3/api-docs/user-service }
      - { name: discharge, url: /v3/api-docs/discharge-service }
      - { name: social-worker-service, url: /v3/api-docs/social-worker-service }
      - { name: schedule-service, url: /v3/api-docs/schedule-service }
      - { name: provider-service, url: /v3/api-docs/provider-service }
      - { name: care-plan-service, url: /v3/api-docs/care-plan-service }

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

internal:
  key: ${INTERNAL_API_KEY}

jwt:
  secret: ${JWT_SECRET}

authentication:
  access-token:
    cookie-name: AccessToken
    redis-key-prefix: ${ACCESS_KEY_PREFIX}
    user-id-claim: sub
    role-claim: role

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.todak_todag.api_gateway: info

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    com.todak_todag.api_gateway: debug

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - configserver:http://${CONFIG_SERVER_HOST}:8888

logging:
  level:
    com.todak_todag.api_gateway: info
