#services:
#
#  # 사용자 서비스.
#  user-service:         # 서비스 추가시 복사 후 해당 부분 변경
#    build:
#      context: ..
#      dockerfile: user-service/Dockerfile
#      args:
#        JAR_FILE: user-service/build/libs/*.jar
#
#    container_name: todak-user-service
#    restart: unless-stopped
#
#    environment:
#      # 로컬 프로파일 사용.
#      SPRING_PROFILES_ACTIVE: local
#
#      # Docker 내부 Config Server 주소.
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
#
#      # Docker 내부 Eureka Server 주소.
#      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
#
#      # Docker 내부 PostgreSQL 주소.
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#
#      # Docker 내부 RabbitMQ 주소.
#      RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
#      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
#      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#
#      # Docker 내부 Zipkin 주소.
#      ZIPKIN_HOST: zipkin
#
#    ports:
#      - "19000:19000"     # 서비스 추가시 복사 후 해당 부분 변경
#
#    # 서비스 상태 확인.
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:19000/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s
#
#    networks:
#      - todak-network
#
#
#
#
## 해당 위치에 위에 양식을 복사 붙여 넣어, 서비스 이름과 포트 번호 수정 후 사용하시면 될 것 같습니다.
#
#
#
#
## compose-infra에서 생성한 공통 네트워크 사용.
#networks:
#  todak-network:
#    external: true

---
services:

  care-plan-service:
    build:
      context: ..
      dockerfile: care-plan-service/Dockerfile
      args:
        JAR_FILE: care-plan-service/build/libs/*.jar

    container_name: todak-care-plan-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: local

      # Docker 내부 Config Server 주소
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888

      # Docker 내부 Eureka Server 주소
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

      # Docker 내부 PostgreSQL 주소
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # Docker 내부 RabbitMQ 주소
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Docker 내부 Zipkin 주소
      ZIPKIN_HOST: zipkin

      INTERNAL_API_KEY: ${INTERNAL_API_KEY}

    ports:
      - "19005:19005"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19005/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - todak-network

  provider-service:
    build:
      context: ..
      dockerfile: provider-service/Dockerfile
      args:
        JAR_FILE: provider-service/build/libs/*.jar

    container_name: todak-provider-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: local

      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888

      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      ZIPKIN_HOST: zipkin

      INTERNAL_API_KEY: ${INTERNAL_API_KEY}

    ports:
      - "19003:19003"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19003/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - todak-network

  schedule-service:
    build:
      context: ..
      dockerfile: schedule-service/Dockerfile
      args:
        JAR_FILE: schedule-service/build/libs/*.jar

    container_name: todak-schedule-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: local

      # Config Server
      CONFIG_SERVER_URL: http://config-server:8888

      # Eureka
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

      # PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Zipkin
      ZIPKIN_HOST: zipkin

      # Internal API Key
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}

    ports:
      - "19004:19004"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19004/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - todak-network

  discharge-service:
    build:
      context: ..
      dockerfile: discharge-service/Dockerfile
      args:
        JAR_FILE: discharge-service/build/libs/*.jar

    container_name: todak-discharge-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: local

      # Config Server
      CONFIG_SERVER_URL: http://config-server:8888

      # Eureka
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

      # PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Zipkin
      ZIPKIN_HOST: zipkin

      # Internal API Key
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}

    ports:
      - "19001:19001"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19001/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - todak-network

  user-service:
      build:
        context: ..
        dockerfile: user-service/Dockerfile
        args:
          JAR_FILE: user-service/build/libs/*.jar

      container_name: todak-user-service
      restart: unless-stopped

      environment:
        SPRING_PROFILES_ACTIVE: local

        # Docker 내부 Config Server 주소
        CONFIG_SERVER_URL: http://config-server:8888

        # Docker 내부 Eureka Server 주소
        EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

        # Docker 내부 PostgreSQL 주소
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        # Docker 내부 Redis 주소
        REDIS_HOST: redis
        REDIS_PORT: 6379

        # Docker 내부 Zipkin 주소
        ZIPKIN_HOST: zipkin

        # 내부 API 인증 정보
        INTERNAL_API_KEY: ${INTERNAL_API_KEY}

        # JWT / 인증 관련
        JWT_SECRET: ${JWT_SECRET}
        ACCESS_KEY_PREFIX: ${ACCESS_KEY_PREFIX}

        # 초기 마스터 계정 정보
        MASTER_USERNAME: ${MASTER_USERNAME}
        MASTER_PASSWORD: ${MASTER_PASSWORD}
        MASTER_NAME: ${MASTER_NAME}

      ports:
        - "19000:19000"

      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:19000/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s

      networks:
        - todak-network


networks:
  todak-network:
    external: true
